modLoader = "javafml"
loaderVersion = "[34,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "diamondeconomy"
version = "${version}"
displayName = "Diamond Economy"
authors = "IAmSneak"
description = '''
Serverside economy mod with diamonds
'''
logoFile = "icon.png"

[[dependencies.diamondeconomy]]
modId = "forge"
mandatory = true
versionRange = "[34,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.diamondeconomy]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.diamondeconomy]]
modId = "cloth-config"
mandatory = true
versionRange = "[4.14.64,)"
ordering = "NONE"
side = "BOTH"